name: flutter_github_actions
packages:
  - packages/**
  - "*"

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze: melos exec -- flutter analyze

  format: melos exec -- flutter format .

  check_format: 
    description: Return exit code 1 if there are any formatting changes 
    run: melos exec -- flutter format --set-exit-if-changed lib test
  
  test: 
    description: Run all tests
    run: melos exec --fail-fast -c 2 -- flutter test --coverage --test-randomize-ordering-seed random
